# Generated by Django 5.1.7 on 2025-06-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=20)),
                ('bus_no', models.CharField(max_length=10)),
                ('out_kms', models.FloatField()),
                ('in_kms', models.FloatField()),
                ('diff', models.FloatField()),
                ('soc', models.CharField(max_length=20)),
                ('time_of_submission', models.TimeField()),
            ],
        ),
    ]
