# Generated by Django 5.1.7 on 2025-06-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryData', '0002_bus_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_data',
            name='diff',
            field=models.FloatField(default=None),
        ),
    ]
