# Generated by Django 5.1.7 on 2025-06-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryData', '0003_alter_bus_data_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_data',
            name='diff',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus_data',
            name='in_kms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bus_data',
            name='soc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
