# Generated by Django 5.1.7 on 2025-06-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryData', '0004_alter_bus_data_diff_alter_bus_data_in_kms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_data',
            name='soc_in',
            field=models.CharField(blank=True, default='Not Provided', max_length=20, null=True),
        ),
    ]
