# Generated by Django 5.1.7 on 2025-06-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryData', '0005_bus_data_soc_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus_data',
            name='user_name',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
