# Generated by Django 5.1.7 on 2025-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryData', '0007_bus_data_in_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus_data',
            name='IN_Time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
